services:
  db:
    image: postgres:17-alpine
    container_name: yfin_postgres
    environment:
      POSTGRES_USER: yfin
      POSTGRES_PASSWORD: yfin
      POSTGRES_DB: yfin_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yfin"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: